name: "is-proxy"

services:
  crowdsec:
    image: docker.io/crowdsecurity/crowdsec:v1.6.10-slim
    container_name: ${CROWDSEC_CONTAINER_NAME-crowdsec}
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    healthcheck:
      interval: 10s
      retries: 15
      timeout: 10s
      test: ["CMD", "cscli", "capi", "status"]
    environment:
      - TZ=${TZ}
      - GID=${GID}
      - COLLECTIONS=${CROWDSEC_COLLECTIONS}
      - PARSERS=${CROWDSEC_PARSERS}
      - ENROLL_INSTANCE_NAME=${CROWDSEC_ENROLL_NAME}
      - ENROLL_TAGS=${CROWDSEC_ENROLL_TAGS}
    volumes:
      - ${CROWDSEC_VOL_CONF}:/etc/crowdsec
      - ${CROWDSEC_VOL_DB}:/var/lib/crowdsec/data
      - ${TRAEFIK_VOL_LOGS}:/var/log/traefik:ro
    networks:
      proxy:
        ipv4_address: ${CROWDSEC_PROXY_IPV4}
    command: -t
    labels:
      - "traefik.enable=false"

  traefik:
    image: docker.io/library/traefik:v3.5.0
    container_name: ${TRAEFIK_CONTAINER_NAME-traefik}
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
      - TZ=${TZ}
      - PUID=${UID}
      - PGID=${GID}
      - CF_DNS_API_TOKEN=${TRAEFIK_DNS_API_TOKEN}
      - CLOUDFLARE_POLLING_INTERVAL=${TRAEFIK_POLLING_INTERVAL}
      - CLOUDFLARE_PROPAGATION_TIMEOUT=${TRAEFIK_PROPAGATION_TIMEOUT}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /run/user/${UID}/podman/podman.sock:/var/run/docker.sock:ro
      - ${TRAEFIK_VOL_STATIC_CONF}:/etc/traefik/traefik_conf.yml:ro
      - ${TRAEFIK_VOL_DYNAMIC_CONF}:/etc/traefik/dynamic_conf/:ro
      - ${TRAEFIK_VOL_ACME}:/etc/traefik/acme.json:rw
      - ${TRAEFIK_VOL_LOGS}:/var/log/traefik:rw
    networks:
      proxy:
        ipv4_address: ${TRAEFIK_PROXY_IPV4}
      private:
        ipv4_address: ${TRAEFIK_PRIVATE_IPV4}
      public:
        ipv4_address: ${TRAEFIK_PUBLIC_IPV4}
      monitoring:
        ipv4_address: ${TRAEFIK_MONITORING_IPV4}
    ports:
      - ${HOST_HTTP_PORT}:80
      - ${HOST_HTTPS_PORT}:443
      - ${HOST_HTTP_PORT_EXTERNAL}:8089
      - ${HOST_HTTPS_PORT_EXTERNAL}:4439
    command:
      - --configFile=/etc/traefik/traefik_conf.yml
    depends_on:
      crowdsec:
        condition: service_healthy
    labels:
      # enable traefik
      - "traefik.enable=true"

      # http config
      - "traefik.http.routers.traefik.entrypoints=web"
      - "traefik.http.routers.traefik.rule=Host(`${TRAEFIK_UI_ADDRESS}`)"

      # https config
      - "traefik.http.routers.traefik-secure.entrypoints=web-secure"
      - "traefik.http.routers.traefik-secure.rule=Host(`${TRAEFIK_UI_ADDRESS}`)"
      - "traefik.http.routers.traefik-secure.middlewares=oidc-auth@file"
      - "traefik.http.routers.traefik-secure.tls=true"

      # ui service config
      - "traefik.http.routers.traefik-secure.service=api@internal"

      # cert resolver config
      - "traefik.http.routers.traefik-secure.tls.certresolver=cloudflare"
      - "traefik.http.routers.traefik-secure.tls.domains[0].main=${TRAEFIK_ROOT_DOMAIN}"
      - "traefik.http.routers.traefik-secure.tls.domains[0].sans=${TRAEFIK_SUB_DOMAINS}"

      # network config
      - "traefik.docker.network=${NET_PRIVATE}"

networks:
  proxy:
    name: ${NET_PROXY}
    external: true
  private:
    name: ${NET_PRIVATE}
    external: true
  public:
    name: ${NET_PUBLIC}
    external: true
  monitoring:
    name: ${NET_MONITORING}
    external: true
