name: "is-proxy"

services:
  traefik:
    image: traefik:3.4.1
    container_name: ${TRAEFIK_CONTAINER_NAME}
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
      - TZ=${TZ}
      - PUID=${UID}
      - PGID=${GID}
      - CF_DNS_API_TOKEN=${TRAEFIK_DNS_API_TOKEN}
      - CLOUDFLARE_POLLING_INTERVAL=${TRAEFIK_POLLING_INTERVAL}
      - CLOUDFLARE_PROPAGATION_TIMEOUT=${TRAEFIK_PROPAGATION_TIMEOUT}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${TRAEFIK_VOL_CONF}:/etc/traefik/
    networks:
      proxy:
        ipv4_address: ${TRAEFIK_PROXY_IPV4}
      private:
        ipv4_address: ${TRAEFIK_PRIVATE_IPV4}
      public:
        ipv4_address: ${TRAEFIK_PUBLIC_IPV4}
      monitoring:
        ipv4_address: ${TRAEFIK_MONITORING_IPV4}
    ports:
      - ${HOST_HTTP_PORT}:80
      - ${HOST_HTTPS_PORT}:443
      - ${HOST_HTTP_PORT_EXTERNAL}:8089
      - ${HOST_HTTPS_PORT_EXTERNAL}:4439
    depends_on:
      crowdsec:
        condition: service_healthy

  pangolin-client:
    image: fosrl/newt
    container_name: ${PANGOLIN_CONTAINER_NAME}
    restart: unless-stopped
    security_opt:
      - no-new-privileges
    environment:
      - PANGOLIN_ENDPOINT=${PANGOLIN_ENDPOINT}
      - NEWT_ID=${PANGOLIN_CLIENT_ID}
      - NEWT_SECRET=${PANGOLIN_CLIENT_SECRET}
    networks:
      proxy:
        ipv4_address: ${PANGOLIN_PROXY_IPV4}

networks:
  proxy:
    name: ${NET_PROXY}
    external: true
  private:
    name: ${NET_PRIVATE}
    external: true
  public:
    name: ${NET_PUBLIC}
    external: true
  monitoring:
    name: ${NET_MONITORING}
    external: true
