name: "st-db-postgres"

services:
  postgres:
    image: docker.io/library/postgres:17-alpine3.22
    container_name: ${PG_CONTAINER_NAME-db-postgres}
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${PG_DATABASE} -U ${PG_ADMIN_USER}"]
      interval: '10s'
      timeout: '30s'
      retries: 5
      start_period: '20s'
    environment:
      - TZ=${TZ}
      - PUID=${UID}
      - PGID=${GID}
      - LANG=${PG_LANG}
      - POSTGRES_DB=${PG_DATABASE}
      - POSTGRES_USER=${PG_ADMIN_USER}
      - POSTGRES_PASSWORD=${PG_ADMIN_PASSWORD}
      - POSTGRES_INITDB_ARGS=${PG_INITDB_ARGS}
      # - POSTGRES_MULTIPLE_DATABASES=${POSTGRES_MULTIPLE_DATABASES} # enabled by init-script
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${PG_VOL_DATA}:/var/lib/postgresql/data/:z,rw
      # - ${PG_INIT_SCRIPT_PATH}:/docker-entrypoint-initdb.d/ # provide custom init-script
    networks:
      store:
        ipv4_address: ${PG_STORE_IPV4}

networks:
  store:
    name: ${NET_STORE}
    external: true
