name: "code-vcs"

services:
  gitea:
    image: gitea/gitea:1.22.6
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
      - TZ=${TZ}
      - USER_UID=${UID}
      - USER_GID=${GID}
      - GITEA__default__RUN_MODE=${GITEA_RUN_MODE}
      - GITEA__default_APP_NAME=${GITEA_APP_NAME}
      - GITEA__database__DB_TYPE=${GITEA_DB_TYPE}
      - GITEA__database__HOST=${GITEA_DB_HOST}
      - GITEA__database__NAME=${GITEA_DB_NAME}
      - GITEA__database__SCHEMA=${GITEA_DB_SCHEMA}
      - GITEA__database__USER=${GITEA_DB_USER}
      - GITEA__database__PASSWD=${GITEA_DB_PASSWORD}
      - GITEA__server__DOMAIN=${GITEA_DOMAIN}
      - GITEA__server__ROOT_URL=${GITEA_ROOT_URL}
      # - GITEA__server__START_SSH_SERVER=${GITEA_START_SSH_SERVER} # if listen port is different from 22
      - GITEA__server__SSH_PORT=${GITEA_SSH_PORT}
      # - GITEA__server__SSH_LISTEN_PORT=${GITEA_SSH_LISTEN_PORT}
      - GITEA__service__DISABLE_REGISTRATION=${GITEA_DISABLE_REGISTRATION}
      - GITEA__service__REQUIRE_SIGNIN_VIEW=${GITEA_REQUIRE_SIGNIN_VIEW}
      - GITEA__openid__ENABLE_OPENID_SIGNIN=${GITEA_ENABLE_OPENID_SIGNIN}
      - GITEA__security__PASSWORD_HASH_ALGO=${GITEA_PASSWORD_HASH_ALGO}
      - GITEA__repository__DEFAULT_BRANCH=${GITEA_DEFAULT_BRANCH}
      - GITEA__repository__USE_COMPAT_SSH_URI=${GITEA_COMPAT_SSH_URI}
      - admin=${GITEA_ADMIN_NAME}
      - pw=${GITEA_ADMIN_PASSWORD}
      - mail=${GITEA_ADMIN_MAIL}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${GITEA_VOL_DATA}:/data/
    networks:
      public:
        ipv4_address: ${GITEA_PUBLIC_IPV4}
    # ports:
    #   - ${HOST_SSH_PORT}:22
    labels:
      # enable traefik
      - "traefik.enable=true"

      # http config
      - "traefik.http.routers.gitea.entrypoints=web"
      - "traefik.http.routers.gitea.rule=Host(`${GITEA_UI_ADDRESS}`)"

      # https config
      - "traefik.http.routers.gitea-secure.entrypoints=web-secure"
      - "traefik.http.routers.gitea-secure.rule=Host(`${GITEA_UI_ADDRESS}`)"
      - "traefik.http.routers.gitea-secure.tls=true"

      # tcp config
      - "traefik.tcp.routers.gitea-ssh.entrypoints=ssh"
      - "traefik.tcp.routers.gitea-ssh.rule=HostSNI(`*`)"

      # ui service config
      - "traefik.http.routers.gitea.service=gitea-ui-svc"
      - "traefik.http.routers.gitea-secure.service=gitea-ui-svc"
      - "traefik.http.services.gitea-ui-svc.loadbalancer.server.port=3000"

      # ssh service
      - "traefik.tcp.routers.gitea-ssh.service=gitea-ssh-svc"
      - "traefik.tcp.services.gitea-ssh-svc.loadbalancer.server.port=${GITEA_SSH_PORT}"

      # network config
      - "traefik.docker.network=${NET_PUBLIC}"

networks:
  public:
    name: ${NET_PUBLIC}
    external: true
