name: "man-gitea"

services:
  gitea:
    image: docker.io/gitea/gitea:1.24
    container_name: ${GITEA_CONTAINER_NAME-gitea}
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
      - TZ=${TZ}
      - USER_UID=${UID}
      - USER_GID=${GID}
      - GITEA__server__OFFLINE_MODE=${GITEA_SRV_OFFLINE_MODE}
      - GITEA__server__ROOT_URL=${GITEA_SRV_ROOT_URL}
      - GITEA__server__SSH_DOMAIN=${GITEA_SRV_SSH_DOMAIN}
      - GITEA__server__SSH_PORT=${GITEA_SRV_SSH_PORT}
      - GITEA__server__SSH_LISTEN_PORT=${GITEA_SRV_SSH_LISTEN_PORT}
      - GITEA__server__START_SSH_SERVER=${GITEA_SRV_START_SSH_SERVER}
      - GITEA__security__SECRET_KEY=${GITEA_SEC_SECRET_KEY}
      - GITEA__security__INTERNAL_TOKEN=${GITEA_SEC_INTERNAL_TOKEN}
      - GITEA__security__PASSWORD_COMPLEXITY=${GITEA_SEC_PASSWORD_COMPLEXITY}
      - GITEA__security__PASSWORD_HASH_ALGO=${GITEA_SEC_PASSWORD_HASH_ALGO}
      - GITEA__service__DISABLE_REGISTRATION=${GITEA_SVC_DISABLE_REGISTRATION}
      - GITEA__service__REQUIRE_SIGNIN_VIEW=${GITEA_SVC_REQUIRE_SIGNIN_VIEW}
      - GITEA__service__DEFAULT_ALLOW_CREATE_ORGANIZATION=${GITEA_SVC_DEFAULT_ALLOW_CREATE_ORGANIZATION}
      - GITEA__service__DEFAULT_ENABLE_TIMETRACKING=${GITEA_SVC_DEFAULT_ENABLE_TIMETRACKING}
      - GITEA__service__DEFAULT_KEEP_EMAIL_PRIVATE=${GITEA_SVC_DEFAULT_KEEP_EMAIL_PRIVATE}
      - GITEA__repository__DEFAULT_PRIVATE=${GITEA_REPO_DEFAULT_PRIVATE}
      - GITEA__repository__DISABLE_HTTP_GIT=${GITEA_REPO_DISABLE_HTTP_GIT}
      - GITEA__repository__ENABLE_PUSH_CREATE_ORG=${GITEA_REPO_ENABLE_PUSH_CREATE_ORG}
      - GITEA__repository__USE_COMPAT_SSH_URI=${GITEA_REPO_USE_COMPAT_SSH_URI}
      - GITEA__mailer__ENABLED=${GITEA_MAILER_ENABLE}
      - GITEA__mailer__FROM=${GITEA_MAILER_FROM_ADDRESS}
      - GITEA__mailer__PROTOCOL=${GITEA_MAILER_PROTOCOL}
      - GITEA__mailer__SMTP_ADDR=${GITEA_MAILER_SMTP_ADDRESS}
      - GITEA__mailer__SMTP_PORT=${GITEA_MAILER_SMTP_PORT}
      - GITEA__mailer__USER=${GITEA_MAILER_SMTP_USER}
      - GITEA__mailer__PASSWD=${GITEA_MAILER_SMTP_PASSWORD}
      - GITEA__oauth2_client__ENABLE_AUTO_REGISTRATION=${GITEA_OAUTH2_ENABLE_AUTO_REG}
      - GITEA__oauth2_client__OPENID_CONNECT_SCOPES=${GITEA_OAUTH2_SCOPES}
      - GITEA__oauth2_client__USERNAME=${GITEA_OAUTH2_USERNAME}
      - GITEA__api__ENABLE_SWAGGER=${GITEA_API_ENABLE_SWAGGER}
      - GITEA__database__DB_TYPE=${GITEA_DB_TYPE}
      - GITEA__database__HOST=${GITEA_DB_HOST}
      - GITEA__database__SSL_MODE=${GITEA_DB_SSL_MODE}
      - GITEA__database__NAME=${GITEA_DB_NAME}
      - GITEA__database__SCHEMA=${GITEA_DB_SCHEMA}
      - GITEA__database__USER=${GITEA_DB_USER}
      - GITEA__database__PASSWD=${GITEA_DB_PASSWORD}
      - GITEA__database__LOG_SQL=${GITEA_DB_LOG_SQL}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${GITEA_VOL_DATA}:/data
    networks:
      public:
        ipv4_address: ${GITEA_PUBLIC_IPV4}
      store:
        ipv4_address: ${GITEA_STORE_IPV4}
    ports:
      - "${HOST_SSH_PORT}:${GITEA_SRV_SSH_LISTEN_PORT}"
    labels:
      # enable traefik
      - "traefik.enable=true"

      # http config
      - "traefik.http.routers.gitea.entrypoints=web-external"
      - "traefik.http.routers.gitea.rule=Host(`${GITEA_UI_ADDRESS}`)"

      # https config
      - "traefik.http.routers.gitea-secure.entrypoints=web-secure-external"
      - "traefik.http.routers.gitea-secure.rule=Host(`${GITEA_UI_ADDRESS}`)"
      - "traefik.http.routers.gitea-secure.tls=true"

      # ui service config
      - "traefik.http.routers.gitea.service=gitea-ui-svc"
      - "traefik.http.routers.gitea-secure.service=gitea-ui-svc"
      - "traefik.http.services.gitea-ui-svc.loadbalancer.server.port=3000"

      # network config
      - "traefik.docker.network=${NET_PUBLIC}"

networks:
  public:
    name: ${NET_PUBLIC}
    external: true
  store:
    name: ${NET_STORE}
    external: true
